[
    {
      "PrvIdn": "100002390",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "VM healthcare",
      "FacilityName": "Chang",
      "LastName": "William",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Anoka",
      "ProviderCity": "Anoka",
      "ProviderCounty": "MN",
      "ProviderState": "55303",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891145",
      "StateLicense": "XXXXA30361",
      "TaxId": "XXXXX537085",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "00:41.0",
      "Keywords": "Small-incision phacoemulsification cataract surgery; minor in-office procedures including small eyelid anomalies and chalazion excisions and laser surgical procedures for secondary cataracts; glaucoma and diabetic complications; General ophthalmology including cataract surgery; glaucoma and diabetic care",
      "Price": "24000"
    },
    {
      "PrvIdn": "100052790",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Swedish ",
      "FacilityName": "Park",
      "LastName": "Lisa",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Bethel",
      "ProviderCity": "Anoka",
      "ProviderCounty": "MN",
      "ProviderState": "55005",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891146",
      "StateLicense": "XXXXG59365",
      "TaxId": "XXXXX537504",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:27.9",
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy; retinal detachments; retinal dystrophies",
      "Price": "13578"
    },
    {
      "PrvIdn": "100064180",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Retinal Associates",
      "FacilityName": "Graham",
      "LastName": "Bell",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Circle Pines",
      "ProviderCity": "Anoka",
      "ProviderCounty": "MN",
      "ProviderState": "55014",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891147",
      "StateLicense": "XXXXA40940",
      "TaxId": "XXXXX667874",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.3",
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy; retinal detachments; retinal dystrophies; Medical and surgical diseases of the retina and vitreous; including age-related macular degeneration; diabetic retinopathy and retinal detachments",
      "Price": "8769"
    },
    {
      "PrvIdn": "100073550",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW",
      "FacilityName": "Webbing",
      "LastName": "Marianna",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Center City",
      "ProviderCity": "Chisago",
      "ProviderCounty": "MN",
      "ProviderState": "55012",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891148",
      "StateLicense": "�XXXXA29800",
      "TaxId": "XXXXX672132",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.4",
      "Keywords": "Pediatric Ophthalmology; Ophthalmology; Cataract Surgery; Strabismus; Pediatric ophthalmology; adult strabismus (misaligned eyes); strabismus surgery and cataract surgery",
      "Price": "18756"
    },
    {
      "PrvIdn": "100079190",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "GPS Associate",
      "FacilityName": "Gatting",
      "LastName": "Bruce",
      "FirstName": "W.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Chisago City",
      "ProviderCity": "Chisago",
      "ProviderCounty": "MN",
      "ProviderState": "55013",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891149",
      "StateLicense": "�XXXXA29801",
      "TaxId": "XXXXX682533",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:03.4",
      "Keywords": "General ophthalmology; dry eye; medical glaucoma Secondary cataract laser surgery (Yag posterior capsulotomy) Minor eyelid lesion removal (excisional biopsies) Punctal plugs for dry eyes Glaucoma laser surgery (Selective laser trabeculoplasty; Argon laser trabeculoplasty; peripheral iridotomy) Electrolysis or forcep epilation for trichiasis (misdirected eyelashes) Examinations for diabetic eye disease and macular degeneration; General comprehensive ophthalmology; dry eye; medical glaucoma; glaucoma laser; after-cataract laser; rosacea; ocular rosacea",
      "Price": "12567"
    },
    {
      "PrvIdn": "100089030",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Providence",
      "FacilityName": "Lee",
      "LastName": "Andrew",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Taylors Falls",
      "ProviderCity": "Chisago",
      "ProviderCounty": "MN",
      "ProviderState": "55084",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891150",
      "StateLicense": "XXXXA12166",
      "TaxId": "XXXXX744468",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:05.9",
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine; Minimally Invasive Surgery",
      "Price": "4539"
    },
    {
      "PrvIdn": "100092080",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW",
      "FacilityName": "Mallard",
      "LastName": "David",
      "FirstName": "L.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Burnsville",
      "ProviderCity": "Dakota",
      "ProviderCounty": "MN",
      "ProviderState": "55306",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891151",
      "StateLicense": "XXXXB12934",
      "TaxId": "XXXXX747058",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:15.2",
      "Keywords": "Sports Medicine; Orthopedics",
      "Price": "4371"
    },
    {
      "PrvIdn": "100102190",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "VM healthcare",
      "FacilityName": "Neilson",
      "LastName": "Abby",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Inver Grove Heights",
      "ProviderCity": "Dakota",
      "ProviderCounty": "MN",
      "ProviderState": "55077",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891152",
      "StateLicense": "XXXXB3963",
      "TaxId": "XXXXX806087",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:08.8",
      "Keywords": "Orthopedic Surgery; Sports Medicine; Orthopedics",
      "Price": "3224"
    },
    {
      "PrvIdn": "100105420",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Swedish ",
      "FacilityName": "Orson",
      "LastName": "Rick",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Lakeville",
      "ProviderCity": "Dakota",
      "ProviderCounty": "MN",
      "ProviderState": "55044",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891153",
      "StateLicense": "XXXXG75426",
      "TaxId": "XXXXX818454",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:42.9",
      "Keywords": "Orthopedic Surgery; Sports Medicine; Hip & Knee Joint Replacement; Orthopedics; Minimally Invasive Surgery",
      "Price": "6500"
    },
    {
      "PrvIdn": "100106860",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Osborne",
      "LastName": "Sarah",
      "FirstName": "M.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Champlin",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55316",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891154",
      "StateLicense": "XXXXA20279",
      "TaxId": "XXXXX833770",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.4",
      "Keywords": "Sports medicine; Orthopedic rehabilitation; Vestibular rehabilitation",
      "Price": "9018"
    },
    {
      "PrvIdn": "100132730",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Gordon",
      "LastName": "John",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Eden Prairie",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55344",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891155",
      "StateLicense": "XXXXA16219",
      "TaxId": "XXXXX873856",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.5",
      "Keywords": "Orthopedics",
      "Price": "6335"
    },
    {
      "PrvIdn": "100133100",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Huck Associates",
      "FacilityName": "Huck",
      "LastName": "Steven",
      "FirstName": "R.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Hopkins",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55305",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891156",
      "StateLicense": "XXXXA16220",
      "TaxId": "XXXXX910802",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:01.5",
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine",
      "Price": "7558"
    },
    {
      "PrvIdn": "100154540",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Peterson Practice",
      "FacilityName": "Peterson",
      "LastName": "Thomas",
      "FirstName": "L.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Minneapolis",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55401",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891157",
      "StateLicense": "XXXXA78358",
      "TaxId": "XXXXX921742",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:08.9",
      "Keywords": "Orthopedic Surgery; Orthopedics; Sports Medicine; Hip & Knee Joint Replacement; Minimally Invasive Surgery",
      "Price": "9405"
    },
    {
      "PrvIdn": "100162870",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Morris",
      "LastName": "Taylor",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Minneapolis",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55414",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891158",
      "StateLicense": "�XXXXA44847",
      "TaxId": "XXXXX924530",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:12.1",
      "Keywords": "Foot and Ankle Surgery; Orthopedic Surgery; Podiatric Surgery; Orthopedics; Podiatry; Minimally Invasive Surgery; Wound Care",
      "Price": "3869"
    },
    {
      "PrvIdn": "100164000",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Eric Eid Private Ltd",
      "FacilityName": "Eid",
      "LastName": "Eric",
      "FirstName": "T.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Minneapolis",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55415",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891159",
      "StateLicense": "XXXXA44694",
      "TaxId": "XXXXX940109",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:07.7",
      "Keywords": "Orthopedic Surgery; Orthopedics; Orthopedic Oncology; Minimally Invasive Surgery; Hip & Knee Joint Replacement",
      "Price": "2957"
    },
    {
      "PrvIdn": "100169810",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "UW sports medicine",
      "FacilityName": "Mars",
      "LastName": "Kevin",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Minneapolis",
      "ProviderCity": "Hennepin",
      "ProviderCounty": "MN",
      "ProviderState": "55435",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891160",
      "StateLicense": "XXXXA45224",
      "TaxId": "XXXXX945477",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:42.7",
      "Keywords": "Orthopedics; Orthopedic Surgery; Sports Medicine; Knee & Shoulder Reconstruction; Minimally Invasive Surgery",
      "Price": "4883"
    },
    {
      "PrvIdn": "100186930",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Pichowsky",
      "LastName": "Robert",
      "FirstName": "S.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Saint Paul",
      "ProviderCity": "Ramsey",
      "ProviderCounty": "MN",
      "ProviderState": "55101",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891161",
      "StateLicense": "XXXXA10747",
      "TaxId": "XXXXX954367",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.5",
      "Keywords": "Ophthalmology; Minimally Invasive Surgery",
      "Price": "9485"
    },
    {
      "PrvIdn": "100205660",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Chen",
      "LastName": "Julian",
      "FirstName": "R.",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Saint Paul",
      "ProviderCity": "Ramsey",
      "ProviderCounty": "MN",
      "ProviderState": "55117",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891162",
      "StateLicense": "XXXXB104621",
      "TaxId": "XXXXX975968",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "01:59.5",
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery",
      "Price": "8582"
    },
    {
      "PrvIdn": "100207670",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "Proliance Surgeons",
      "FacilityName": "Carlson",
      "LastName": "Jeffery",
      "FirstName": "",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Saint Paul",
      "ProviderCity": "Ramsey",
      "ProviderCounty": "MN",
      "ProviderState": "55126",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891163",
      "StateLicense": "XXXXB104622",
      "TaxId": "XXXXX019942",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:01.6",
      "Keywords": "Ophthalmology; Vitreoretinal Surgery; Minimally Invasive Surgery",
      "Price": "6738"
    },
    {
      "PrvIdn": "100215340",
      "ProviderNpi": "1/1/2010",
      "EffectiveDt": "",
      "TermDt": "",
      "FacilityName": "Doctor Last Name 20",
      "LastName": "Doctor First Name 20",
      "FirstName": "Doctor Middle Name 20",
      "MiddleName": "MD",
      "SuffixName": "",
      "ProviderSpecialityCode": "",
      "ProviderSpecialityDesc": "Elk River",
      "ProviderCity": "Sherburne",
      "ProviderCounty": "MN",
      "ProviderState": "55330",
      "ProviderZip": null,
      "DeaNumber": "XXX-BA7891164",
      "StateLicense": "XXXXA30933",
      "TaxId": "XXXXX036581",
      "CreateTimestamp": "userSysNbr",
      "ModifyTimestamp": "02:05.9",
      "Keywords": "Ophthalmology; Cataract Surgery; Cornea & Eye Disease; Minimally Invasive Surgery",
      "Price": "2378"
    }
  ]